# Generated by Django 4.2.16 on 2024-10-03 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_location_order_waiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.client')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.location')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.order')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.waiter')),
            ],
        ),
    ]
